### ISSUE TITLE
Access elements of param permutations

### ISSUE THREAD

**Issue by amaslenn** [open-mpi/mtt-legacy#2]
Consider the following `MPI Details` and `exec`:
```ini
[MPI Details: Open MPI]
params = &enumerate(opt1, opt2)
exec = mpirun @params@ -np &test_np() &test_executable() &my_funclet()
```

Is there any way to access `opt1`/`opt2` inside `&my_funclet()`?

I see it like this:
```
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt2)
```

but adding `@params@` as an option simply multiplies the number of my cases.

**Comment by amaslenn** [comment]
@jsquyres could you please take a look and maybe suggest something?

**Comment by jsquyres** [comment]
IIRC, the way `@foo@` expansion works, we actually build up an array of values for `exec` and do the substitution in each of the array values.  I.e., there's no external tracking / reference of what value was substituted in -- you can think of the expansion as resulting in something like this in Perl (it doesn't happen exactly this way, but it's close enough for this discussion):

```perl
$exec[0] = "mpirun opt1 -np &test_np() &test_executable() &my_funclet(...)";
$exec[1] = "mpirun opt2 -np &test_np() &test_executable() &my_funclet(...)";
```

I.e., there's nothing tracking that the `opt1` in `$exec[0]` is actually the first element from `@params@`, and the `opt2` in `$exec[1]` is actually the second element from `@params@`.

That being said, I don't know exactly how the expansion of the following would work:

```ini
[MPI Details: Open MPI]
params = &enumerate(opt1, opt2)
exec = mpirun @params@ -np &test_np() &test_executable() &my_funclet(@params@)
```

There's a better-than-even chance that that would actually end up expanding as

```
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt2)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt2)
```

...but it *might* expand the way you want it:

```
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt2)
```

...or it might blow up / not work at all...?

🤷‍♂

**Comment by amaslenn** [comment]
Thanks for the quick reply!

I've tried that option:
```ini
exec = mpirun @params@ -np &test_np() &test_executable() &my_funclet(@params@)
```
This really doubles my cases producing this:
```
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt1 -np &test_np() &test_executable() &my_funclet(opt2)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt1)
mpirun opt2 -np &test_np() &test_executable() &my_funclet(opt2)
```

It doesn't blow up and the result is expected for my understanding of how MTT generate cases. Just hoped for some secret options/variables/anything to achieve what I need :)

Thanks!
